### ISSUE TITLE
USER STORY: Collecting Data from poll 

### ISSUE THREAD

**Issue by TashaTJ** [TashaTJ/My-First-Agile-Project#4]
as an **administrator** I can **download collected data from an automated google sheet** so that I can **Keep record of previous polls including voting details**

## Acceptance criteria: 

* Acceptance Criteria 1: Google sheet must contain 3 data fields that match the data fields on the poll 
* Acceptance Criteria 2: The 'Best Timings' data must be a dropdown menu with 3 different options to choose from 
* Acceptance Criteria 3: The sheet must allow anonymous entries in the "name" field

## Tasks
  
- [ ] link 2 x APIs for google sheets and google drive
- [ ] write a python function to generate the date of data entry 
- [ ] Design the poll (HTML & CSS) and include a dropdown menu for the timings options
- [ ] test functionality
